### PR TITLE
Add default format detection for Databook.load()

### PR DESCRIPTION
**Pull request by nuno-andre**
Unlike `Dataset.load()`, which defaults to `None`, `Databook.load()` needs an explicit _format_ value.

This code raises `TypeError: load() missing 1 required positional argument: 'format'`:

```python
with open('data.xlsx', 'rb') as fh:
    dbook = Databook().load(fh)
```

This PR also (without api changes):
- Adds some tests.
- Adds some exception messages.
- Fixes and updates core's docstrings and api docs.
- Simplifies `Databook._package()`.
- _LBYL &rarr; EAFP_ in `.load()`.
- Adds an `UnsupportedFormat` exception for when `detect_format` fails to avoid the _"Format 'None' cannot be loaded.'"_ message.

### CODE REVIEW

**Review by claudep — CHANGES_REQUESTED** [review]
Please do not mix so many issues in one commit. Each issue should be a separate commit, even separate PRs. For max line length, it's still something undecided, I'd rather not change it for now.

**Comment by nuno-andre** [comment]
Not the best PR, indeed. It's a bunch of minor changes prior to push some adapters we're using in prod.

So, in order to ease these and other contributions, would you consider setting those conventions and adding a code formatter as a pre-commit hook? Are there guidelines for this at Jazzband?

**Comment by claudep** [comment]
Frankly, I think it would be better to let formatting issues aside and concentrate on "real" changes instead, separated by concern.

**Comment by nuno-andre** [comment]
Code formatting reduces diffs and merging conflicts, and saves developers' time. In what sense is not a "real" change?

**Comment by hugovk** [comment]
Thanks for the PR!

Formatting is a real change, but please create another PR or issue for that (or see https://github.com/jazzband/tablib/issues/401 and linked PRs) and keep this one focused. If anything, it'll help us get this format detection reviewed and merged sooner.

Thank you!

**Comment by nuno-andre** [comment]
Right, I should have searched for such an issue... I'm going to close this PR (it's already too unfocused) and I'll open separate PRs.

Anyway, are there some guidelines for linting and code formatting at Jazzband?

**Comment by hugovk** [comment]
It varies by project. This one has some linting done by [pre-commit](https://pre-commit.com/), which you run using the pre-commit commands or with `tox -e lint`. The CI will check it too.

**Pull request closed without merging**
