### PR TITLE
Implement feature new format: Cli. Generate adapter for  tabulate. Th…

### PR DESCRIPTION
**Pull request by xdanielsb**
…is close issue #340

 Write respective tests.

### CODE REVIEW

**Comment by claudep** [comment]
@xdanielsb Why did you commit that?
It wasn't approved and the tests don't pass. Please stop commit patches in tablib yourself. I'll do the revert myself.

**Comment by claudep** [comment]
Reverted in d21bd109087

**Comment by xdanielsb** [comment]
salut @jezdez , is it okay if I restore the branch feature-cli-format?, if I lose the repo in my computer I will be able to recover the work done  and continue improving it  to meet the guidelines of JazzBand

**Comment by jezdez** [comment]
Sure, if you plan to resubmit the branch in a new pull request for code review soon, feel free to  restore the branch on GitHub.

**Comment by xdanielsb** [comment]
much obliged @jezdez, I'd like to improve my pratiques in python, to generate better pull request in this community, do you have any advice or resource that could help me out?, anything will be appreciate it :v

**Comment by claudep** [comment]
Daniel, it's not a problem to try, experiment, make errors, as we all do. Just avoid to commit to the master branch of modules where you are not a main contributor.

**Comment by jezdez** [comment]
@xdanielsb That's a great question and there are a lot of good resources out there that help you get better with that, like the the video series from GitHub about best practices: https://resources.github.com/videos/github-best-practices/

I encourage you to try things out of course and we welcome any contributor, but make sure to get a feel for what is appropriate and what could create more work for your fellow Jazzband members. The singular goal of Jazzband is to share the responsibility of maintaining the projects, and that implies that you're able to do the maintenance. I'm afraid that it's not Jazzband's mission to provide organized in-depth training or mentorship at the moment, but of course I can't speak for all members. I know this isn't a satisfying situation, but there are many other projects like the [OpenTechSchool](https://www.opentechschool.org/) that have a more structured program to help learners grow.

**Comment by hugovk** [comment]
My tip is to experiment using a personal fork of the repo. 

I do virtually all my open source stuff from my own personal fork, even if I do have rights to make a branch in the main repo. 

I also usually turn on the CI for my fork too, so I know if the tests pass on a branch before creating a PR.

**Comment by xdanielsb** [comment]
Claude, Jannis, Hugo I appreciate so much your tips, thanks so much

**Pull request merged**
