### PR TITLE
Get row method

### LINKED ISSUE #24: get_row, get_col methods

### PR DESCRIPTION
**Pull request by yoonthegoon**
Fixes #24 get_row, get_col methods

### CODE REVIEW

**Comment by yoonthegoon** [comment]
Would one of you please take a look when you get the chance?
I'm looking to try to clean out some old issues on here when I get time. @hugovk @claudep

**Comment by hugovk** [comment]
Thanks for the PR.

https://github.com/jazzband/tablib/pull/28 added `get_col`, should this be named `get_row` instead of `get` (as suggested in https://github.com/jazzband/tablib/issues/24)?

**Comment by yoonthegoon** [comment]
> Thanks for the PR.
> 
> 
> 
> https://github.com/jazzband/tablib/pull/28 added `get_col`, should this be named `get_row` instead of `get` (as suggested in https://github.com/jazzband/tablib/issues/24)?

i was originally gonna, but all the row methods in the class don't have `row` in their names while all the column methods do have `col`. kenneth also commented on the original issue that the methods he wanted were `get` to return a row by index and `get_col` for column by index.

**Review by hugovk — APPROVED** [review]
Ah yes, good point!

Thank you!

**Comment by claudep** [comment]
Did you check if the docs should be updated somewhere?

**Comment by yoonthegoon** [comment]
I built the docs locally and it looks like it added it by me, so the existing rst files appear to pick it up.
`docs/_build/*` is in the `.gitignore` so I don't think there's any need for me to commit a build.
Built docs are [here](https://tablib--557.org.readthedocs.build/en/557/api.html#tablib.Dataset.get) and look good to me.

**Comment by hugovk** [comment]
We could add an example to the quickstart guide:

https://tablib.readthedocs.io/en/stable/tutorial.html#selecting-rows-columns

**Comment by claudep** [comment]
The "add type validation" commit should not be part of this PR.

**Comment by yoonthegoon** [comment]
> The "add type validation" commit should not be part of this PR.

Yeah I just noticed it changed more than I intended. 
Lemme fix that real quick

**Comment by claudep** [comment]
:medal_sports:

**Pull request merged**
