### PR TITLE
Format code with Black and isort

### LINKED ISSUE #401: Consider enforcing flake8, black and isort
As part of #398 I've added disabled calls to flake8 including a commented-out installation of the flake8-black and flake8-isort plugins. I would suggest to run black and isort once over the code base and enabling both plugins to have a positive long-term effect on code quality. I didn't make this part of #398 since it's not a hard requirement for Jazzband projects (yet) but I've seen more and more projects move to that strategy.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #401 

* Format code with Black 
* Add some Black-compatible config to `.flake8`
  * E203, W503 are not compatible with PEP 8, skip them
  * line lengths match Black's default

* sort imports with isort
  * Move isort config to the new central `pyproject.toml`, add new config to place nicely with Black

* Fix Flake8 errors

* Remove some Python 2 code: `__cmp__` and `cmp`

* Add Black/isort checks to tox and the CI

To autofix code locally:
```sh
pip install -U black isort
black .
isort -y
```

(I'll do pre-commit in another PR.)

### CODE REVIEW

**Comment by claudep** [comment]
Thanks, but this will break (again) my PR #395. Do you think you would be able to review it before pushing this one?

**Comment by hugovk** [comment]
Sure, let's get #395 in before this. I'm not too familiar with the internals of Tablib and would rather stick to more general things like testing, so would rather someone else reviewed it. I've left a comment on the PR's issue 👍

**Comment by claudep** [comment]
I still pushed the isort part as it is less invasive that black.

**Comment by claudep** [comment]
Any idea why current master fails with isort? (cannot reproduce locally)

**Comment by hugovk** [comment]
Probably because it's missing the isort config changes in `pyproject.toml`, specifically:
```toml
known_third_party = ["MarkupPy", "odf", "openpyxl", "pkg_resources", "setuptools", "tablib", "xlrd", "xlwt", "yaml"]
```

I suggest always making a PR and only committing directly to `master` for very minor changes. (In fact, we could disable committing directly to `master` in the repo settings.)

**Comment by claudep** [comment]
Thanks for the tip and sorry for not using a PR for this change.

**Comment by hugovk** [comment]
You're welcome, and no problem :)

**Comment by hugovk** [comment]
Closing, will send new PRs.

First Black, then another for Flake8. Will be easier to review separately.

**Pull request closed without merging**
