### PR TITLE
Some documentation fixes

### PR DESCRIPTION
**Pull request by gthieleb**

### CODE REVIEW

**Comment by timofurrer** [comment]
Please resolve the merge conflicts. Thanks :tada:

**Comment by hugovk** [comment]
Merge conflicts resolved.

**Comment by claudep** [comment]
This looks to be closely related to the format refactoring suggested in #395. Let's wait a bit before pushing.

**Comment by hugovk** [comment]
What's the status of this PR? Still relevant after #395 has been merged?

**Comment by claudep** [comment]
I think the new formats documentation is now explicit enough about csv import/export options. Sorry for taking too long to review.

**Pull request closed without merging**
