### PR TITLE
No __cmp__ or cmp in Python 3

### PR DESCRIPTION
**Pull request by hugovk**
Cherry-picked from #428, found by Flake8.

### CODE REVIEW

**Comment by claudep** [comment]
I wonder if we should replace this by rich comparison methods (https://portingguide.readthedocs.io/en/latest/comparisons.html#rich-comparisons).

**Comment by hugovk** [comment]
That might be a good idea. Or do we have anywhere in code that is comparing these fields? How might a user do so, and how is it useful?

**Comment by claudep** [comment]
I must admit I'm not more advanced on this question. It's just keeping the functionality without much thinking...

**Comment by hugovk** [comment]
I've updated the PR to add rich comparisons, with tests.

I did it by comparing the `repr(self)` with `repr(other)`.

Previously it was comparing `self.name` with `str(other).upper()` which are different ways of looking at the data.

For example, these two fields would be different:

```python
a = fields.DbfCharacterFieldDef("abc", self.length)
b = fields.DbfCharacterFieldDef("abc", self.length)
```

Because `self.name` of `a` is `ABC` and `str(other).upper()` of `b` is `ABC        C  10   0`.

**Comment by claudep** [comment]
That's great! Do you think you could simplify a bit by using the `total_ordering` decorator?

**Comment by hugovk** [comment]
Done!

**Comment by hugovk** [comment]
Done!

image

**Comment by claudep** [comment]
Perfect, thanks.

**Pull request merged**
